[package]
name = "hex"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.44"
quote = "0.6.13"
palette = "0.5.0"
iced_native = { git = "https://github.com/iced-rs/iced", rev = "35c4ad6" }